# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/luukieboy/Documents/thesis/hdl/projects/adrv9364z7020/ccbob_lvds/adrv9364z7020_ccbob_lvds.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
# IP: The module: 'system_axi_iic_main_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/luukieboy/Documents/thesis/hdl/projects/adrv9364z7020/ccbob_lvds/adrv9364z7020_ccbob_lvds.gen/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_iic_main_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/luukieboy/Documents/thesis/hdl/projects/adrv9364z7020/ccbob_lvds/adrv9364z7020_ccbob_lvds.gen/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_iic_main_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/luukieboy/Documents/thesis/hdl/projects/adrv9364z7020/ccbob_lvds/adrv9364z7020_ccbob_lvds.srcs/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0.xci
# IP: The module: 'system_axi_iic_main_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/luukieboy/Documents/thesis/hdl/projects/adrv9364z7020/ccbob_lvds/adrv9364z7020_ccbob_lvds.gen/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_iic_main_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/luukieboy/Documents/thesis/hdl/projects/adrv9364z7020/ccbob_lvds/adrv9364z7020_ccbob_lvds.gen/sources_1/bd/system/ip/system_axi_iic_main_0/system_axi_iic_main_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_iic_main_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
